spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vithy
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
  ai:
    model: cloud

auth0:
  domain: ${AUTH0_DOMAIN:}
  audience: ${AUTH0_AUDIENCE:}
